python scripts/eval/truthfulqa.py --model TempModel:QWEN_32B_SGTR_1
python scripts/eval/truthfulqa.py --model TempModel:QWEN_32B_SGTR_2
python scripts/eval/truthfulqa.py --model TempModel:QWEN_32B_SGTR_3
python scripts/eval/truthfulqa.py --model TempModel:QWEN_32B_SGTR_4
python scripts/eval/truthfulqa.py --model TempModel:QWEN_32B_ASGTR_0
python scripts/eval/truthfulqa.py --model TempModel:QWEN_32B_ASGTR_1
python scripts/eval/truthfulqa.py --model TempModel:QWEN_32B_ASGTR_2
python scripts/eval/truthfulqa.py --model TempModel:QWEN_32B_ASGTR_3
python scripts/eval/truthfulqa.py --model TempModel:QWEN_32B_ASGTR_4