"""
Temporary models registry for experimental/finetuned models.

This file can be:
1. Manually edited to add/remove temporary models
2. Auto-generated by finetuning scripts using models_utils.add_temp_model()
3. Used to promote models to models.py manually

Format matches the official models.py for easy promotion.
"""

from enum import Enum
from utils.models import ModelMetadata, Backend


class TempModel(Enum):
    """
    Temporary model definitions for experimental/finetuned models.

    To promote a model to production (manual process):
    1. Copy the enum entry to Model class in utils/models.py
    2. Copy the TEMP_MODEL_METADATA entry to MODEL_METADATA in utils/models.py
    3. Delete the entry from this file

    This ensures all changes to official models are intentional and reviewed.
    """
    # ADD-TEMP-MODEL-BEGIN #
    # ADD-TEMP-MODEL-END #


TEMP_MODEL_METADATA = {
    """
    Example format:
    "hf_qwen_7b_exp_v1": ModelMetadata(
        model_id="atagade/qwen_7b_experiment_v1",
        backend=Backend.HUGGING_FACE,
        is_lora=True
    ),
    """
    # ADD-TEMP-MODEL-METADATA-BEGIN #
    # ADD-TEMP-MODEL-METADATA-END #
}
